# Generated by Django 4.1.3 on 2024-08-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_customer_catgeory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Catgeory',
        ),
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
